rules:
  # checks if file ends in a newline character
  end-of-file:
    # set to true to enable this rule
    enable: true

    # set to true to disable autofix (if enabled globally)
    disable-autofix: false

    # will be ignored only by this rule
    ignore:
      - docs/__init__.py
      - docs/image/inter_process_communication.drawio
      - docs/image/what_is_scenario_testing_framework.drawio
      - openscenario/openscenario_utility/openscenario_utility/__init__.py
      - openscenario/openscenario_utility/resource/openscenario_utility
      - test_runner/scenario_test_runner/resource/scenario_test_runner
      - test_runner/scenario_test_runner/scenario_test_runner/__init__.py

    # if true also checks if file ends in a single newline character
    single-new-line: true
