/**:
  ros__parameters:
    k_us: 0.006473
    k_us_vx_lo: 1.7504
    k_us_vx_hi: 10.959
    steer_time_constant: 0.150
    steer_time_delay: 0.066
    steer_dead_band: 0.0028536
    steer_bias: 1.346e-05
    debug_steer_scaling_factor: 0.99206
    steer_rate_lim: 0.4
    acc_time_constant: 0.17904
    acc_time_delay: 0.1
