float64 acceleration 3 # should be over 0
float64 deceleration 5 # should be over 0

# from OpenSCENARIO 1.2 DynamicConstraints
float64 max_acceleration
float64 max_acceleration_rate
float64 max_deceleration
float64 max_deceleration_rate
float64 max_speed

float64 lane_change_distance 20 # should be over 0

float64 stop_margin 3 # should be over 0

float64 follow_distance 20 # should be over 0

bool see_around true # entity see around or not
