# acceleration should be over 0
float64 acceleration 3

# float64 max_acceleration # TODO @hakuturu583

# float64 max_acceleration_rate # TODO @hakuturu583

# deceleration should be over 0
float64 deceleration 5

# float64 max_deceleration # TODO @hakuturu583

# float64 max_deceleration_rate # TODO @hakuturu583

# float64 max_speed # TODO @hakuturu583

# lane_change_distance should be over 0
float64 lane_change_distance 20

# stop_margin should be over 0
float64 stop_margin 3

# follow_distance should be over 0
float64 follow_distance 20

# entity see around or not
bool see_around true
