@startuml
title autoware API
allow_mixing

interface ros2topic

Node SimulatorAPI {
  class awapi_accessor
}

awapi_accessor -> ros2topic

Node Autoware {
  Node awapi_adaptor
  interface engage_command
  interface lanechange_request
}

ros2topic -> awapi_adaptor
awapi_adaptor -down-> engage_command
awapi_adaptor -down-> lanechange_request

@enduml