@startuml
allow_mixing
title WholeArchitecture

interface ros2lifecycle

Node openscenario_interpreter_node {
  class EntityManager
  class TrafficLightManager
  class MetricsManager
  class scenario_simulator::API
  class ZeroMQRequestSocket
  scenario_simulator::API o-- EntityManager
  scenario_simulator::API o-- TrafficLightManager
  scenario_simulator::API o-- MetricsManager
  TrafficLightManager -right-> EntityManager
  EntityManager -right-> MetricsManager
  class EgoEntity
  class VehicleEntity
  class PedestrianEntity
  EntityManager o-- EgoEntity
  EntityManager o-- VehicleEntity
  EntityManager o-- PedestrianEntity
  class AwapiAccessor
  EgoEntity o-- AwapiAccessor
}

openscenario_interpreter_node -up-> ros2lifecycle

ros2lifecycle -right-> openscenario_interpreter_node

Node test_runner_node {
}

test_runner_node -down-> openscenario_interpreter_node
test_runner_node -down-> ros2lifecycle
ros2lifecycle -up-> test_runner_node

Node Autoware {
  Interface AutowareAPI
}

interface ros2launch

test_runner_node --left-> ros2launch
ros2launch -down-> Autoware

interface "ZEROMQ (TCP)"

scenario_simulator::API -left-> ZeroMQRequestSocket
ZeroMQRequestSocket -right-> scenario_simulator::API
ZeroMQRequestSocket -up-> "ZEROMQ (TCP)"
"ZEROMQ (TCP)" -down-> ZeroMQRequestSocket

Node Simulator {
  class ZeroMQReplySocket
}

"ZEROMQ (TCP)" -up-> ZeroMQReplySocket
ZeroMQReplySocket -down-> "ZEROMQ (TCP)"

@enduml