name: Check msgs / srvs update
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  check_message_updates:
    name: Check message updates
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: scenario_simulator_v2

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          uvx --from vcstool vcs import scenario_simulator_v2/external < scenario_simulator_v2/dependency_humble.repos

      - name: Install Python dependencies
        run: |
          cd scenario_simulator_v2
          uv sync --locked --all-extras --dev

      - name: Check updates
        shell: bash
        run: |
          cd scenario_simulator_v2
          uv run python3 .github/msgs_checker.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: 1203
