name: Docker Arm64
on:
  pull_request:
    paths:
      - "**"
      - "!docs/**"
      - "!README.md"
      - "!CONTRIBUTING.md"
      - "!.github/**"
      - ".github/workflows/Docker.yaml"
      - "!mkdocs.yml"
      - "!pyproject.toml"
      - "!poetry.lock"
  workflow_dispatch:
    inputs:
      version:
        description: version of the scenario_simulator_v2
        required: true

jobs:
  push_docker:
    name: Push Docker Arm64 Image
    runs-on: ubuntu-22.04
    timeout-minutes: 720
    strategy:
      matrix:
        rosdistro: [humble]
        arch: [arm64]
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Install docker for ubuntu runner
        uses: docker/setup-buildx-action@v3

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3

      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (${{ matrix.arch }})
        if: github.event_name == 'pull_request'
        run: 
          docker buildx build --platform linux/arm64/v8 -t ghcr.io/tier4/scenario_simulator_v2:humble --build-arg ROS_DISTRO=humble .

      - name: Build and push (${{ matrix.arch }})
        if: github.event_name == 'workflow_dispatch'
        run:           
          docker buildx build --platform linux/arm64/v8 -t ghcr.io/tier4/scenario_simulator_v2:humble --build-arg ROS_DISTRO=humble --push .
