name: Docker
on:
  pull_request:
    paths:
      - "**"
      - "!docs/**"
      - "!README.md"
      - "!CONTRIBUTING.md"
      - "!.github/**"
      - ".github/workflows/Docker.yaml"
      - "!mkdocs.yml"
      - "!pyproject.toml"
      - "!sonar-project.properties"
      - "!uv.lock"
  push:
    branches:
      - master
    paths:
      - "**/package.xml"
  workflow_dispatch:
    inputs:
      version:
        description: version of the scenario_simulator_v2
        required: true

env:
  IMAGE_BASE: ghcr.io/tier4/scenario_simulator_v2
jobs:
  bake-full-development:
    uses: docker/github-builder/.github/workflows/bake.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      target: full_development
      meta-flavor: |
        prefix=humble-
        suffix=-devel
      meta-images: ghcr.io/tier4/scenario_simulator_v2
      meta-tags: |
        type=semver,pattern={{version}}
        type=raw,value=latest,enable={{is_default_branch}}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  bake-full-runtime:
    uses: docker/github-builder/.github/workflows/bake.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      target: full_runtime
      meta-flavor: |
        prefix=humble-
        suffix=-runtime
      meta-images: ghcr.io/tier4/scenario_simulator_v2
      meta-tags: |
        type=semver,pattern={{version}}
        type=raw,value=latest,enable={{is_default_branch}}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  bake-full-desktop:
    uses: docker/github-builder/.github/workflows/bake.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      target: full_desktop
      meta-flavor: |
        prefix=humble-
      meta-images: ghcr.io/tier4/scenario_simulator_v2
      meta-tags: |
        type=semver,pattern={{version}}
        type=raw,value=latest,enable={{is_default_branch}}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
