name: Run-Docker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: setup docker
      uses: docker-practice/actions-setup-docker@master
    - name: pull docier image
      run: docker pull tier4/scenario_simulator_v2:latest
    - name: run scenario_test
      uses: addnab/docker-run-action@v3
      with:
        image: tier4/scenario_simulator_v2:latest
        run: ros2 launch scenario_test_runner scenario_test_runner.launch.py workflow:='/home/ubuntu/Desktop/scenario_simulator_ws/install/scenario_test_runner/share/scenario_test_runner/workflow_example.yaml'