name: Run Docker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: docker-practice/actions-setup-docker@master
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8