name: Run-Docker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
    branches:
      - master
      
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - name: setup docker
      uses: docker-practice/actions-setup-docker@master
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install rocker
      run: pip3 install rocker
    - name: pull docker images
      run: docker pull tier4/scenario_simulator_v2