name: Run-Docker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
    - name: setup docker
      uses: docker-practice/actions-setup-docker@master
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install rocker
      run: pip3 install rocker
    - name: pull docker images
      run: docker pull tier4/scenario_simulator_v2
    - name: run scenario test
      run: rocker --x11 scenario_simulator_v2 ros2 launch scenario_test_runner scenario_test_runner.launch.py workflow:='$(find-pkg-share scenario_test_runner)/workflow_example.yaml' && ros2 run scenario_test_runner result_checker /tmp/scenario_test_runner/result.junit.xml