# Autogenerated by mrt_cmake_modules for python api

from os.path import dirname, basename, isfile
from glob import glob

# automatically import all files in this module
modules = glob(dirname(__file__)+"/*.so")
__all__ = [ basename(f)[:-3] for f in modules ]

for module_name in __all__:
    from importlib import import_module
    module = import_module(__name__ + "." + module_name)
    if len(__all__) == 1:
        globals().update(module.__dict__)
    del module
del modules

